/*
* @Author: dxx
* @Email: dxxtalking@163.com
* @Date:   2020-12-24 11:19:21
* @Last Modified by:   dxx
* @Last Modified time: 2021-01-25 15:02:34
*/
export const sideBarData = {
	menu:[
		{
			id:"01",
			icon:"el-icon-house",
			title:"我的工作台",
			path:"/index",
			sub:null,
		},
		{
			id:"02",
			icon:"el-icon-edit-outline",
			title:"系统配置",
			path:"/system",
			sub:null,
		},
		{
			id:"03",
			icon:"el-icon-date",
			title:"资源管理",
			path:"/resources",
			sub:null,
		},
		{
			id:"04",
			icon:"el-icon-lock",
			title:"权限管理",
			path:"/auth",
			sub:[
				{
					id:"04-01",
					icon:"",
					title:"部门管理",
					path:"/auth/dept",
					sub:null,
				},
				{
					id:"04-02",
					icon:"",
					title:"用户管理",
					path:"/auth/user",
					sub:null,
				},
				{
					id:"04-03",
					icon:"",
					title:"角色管理",
					path:"/auth/role",
					sub:null,
				},
			],
		},
		{
			id:"05",
			icon:"el-icon-circle-check",
			title:"项目配置",
			path:"/project",
			sub:[
				{
					id:"05-01",
					icon:"",
					title:"类别配置",
					path:"/project/category",
					sub:null,
				},
				{
					id:"05-02",
					icon:"",
					title:"项目节点配置",
					path:"/project/projectnode",
					sub:null,
				},
				{
					id:"05-03",
					icon:"",
					title:"项目资源分配",
					path:"/project/distribution",
					sub:null,
				},
			],
		},
		{
			id:"06",
			icon:"icon-lan2",
			title:"审核流程管理",
			path:"/auditProcess",
			sub:null,
		},
		{
			id:"07",
			icon:"el-icon-office-building",
			title:"厂商管理",
			path:"/manufacturer",
			sub:[
				{
					id:"07-01",
					icon:"",
					title:"厂商用户管理",
					path:"/manufacturer/user",
					sub:null,
				},
				{
					id:"07-02",
					icon:"",
					title:"厂商子账号管理",
					path:"/manufacturer/sub",
					sub:null,
				},
			],
		},

		{
			id:"08",
			icon:"el-icon-message",
			title:"信息管理",
			path:"/message",
			sub:null,
		},
		{
			id:"09",
			icon:"el-icon-document",
			title:"文档资源管理",
			path:"/document",
			sub:null,
		},
		{
			id:"10",
			icon:"icon-coin-yen",
			title:"经费管理",
			path:"/funds",
			sub:null,
		},
		{
			id:"11",
			icon:"el-icon-postcard",
			title:"日志管理",
			path:"/log",
			sub:null,
		},
		// {
		// 	id:"11",
		// 	icon:"el-icon-info",
		// 	title:"版本管理",
		// 	path:"/version",
		// 	sub:null,
		// },
	],
}